name: haneke-conda-env
channels:
  - anaconda-fusion
  - defaults
dependencies:
  - beautifulsoup4==4.8.0
  - certifi
  - chardet
  - idna
  - numpy
  - pandas
  - python-dateutil
  - pytz
  - requests
  - selenium
  - six
  - soupsieve
  - urllib3
